Django/StuffControl/urls.py
from django.conf.urls import patterns, include, url

from rest_framework.authtoken import views

from django.contrib import admin
admin.autodiscover()

from userprofiles.views import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'StuffControl.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^entry/', 'userprofiles.views.entry', name='entry'),
    url(r'^logout/', 'userprofiles.views.logout_view', name='logout_view'),

    url(r'^thing/(\d+)', 'things.views.thing', name='thing'),
    url(r'^newthing/', 'things.views.new_thing', name='new_thing'),
    url(r'^create_newthing/', 'things.views.create_new_thing', name='create_new_thing'),
    url(r'^delete_thing/(\d+)', 'things.views.delete_thing', name='delete_thing'),
    url(r'^order_controller/', 'things.views.order_controller', name='order_controller'),
    url(r'^sensor_value/', 'things.views.sensor_value', name='sensor_value'),
    url(r'^add_automaticcontroller/', 'things.views.add_automaticcontroller', name='add_automaticcontroller'),
    url(r'^get_automaticcontroller/', 'things.views.get_automaticcontroller', name='get_automaticcontroller'),
    url(r'^change_check/(\d+)/(\d+)', 'things.views.change_check', name='change_check'),
    url(r'^delete_automatic/(\d+)', 'things.views.delete_automatic', name='delete_automatic'),
    url(r'^getthings/', 'things.views.getthings', name='getthings'),


    url(r'^newcamera/', 'cameras.views.new_camera', name='new_camera'),
    url(r'^create_newcamera/', 'cameras.views.create_new_camera', name='create_new_camera'),
    url(r'^camera/(\d+)', 'cameras.views.camera', name='camera'),
    url(r'^getcameras/', 'cameras.views.getcameras', name='getcameras'),

    url(r'^rest_login/', 'userprofiles.views.Rest_Login', name='rest_login'),
    url(r'^rest_get_things/', 'userprofiles.views.Rest_Get_Things', name='rest_get_things'),
    url(r'^rest_get_cameras/', 'userprofiles.views.Rest_Get_Cameras', name='rest_get_cameras'),
    url(r'^rest_get_thing_elements/(\d+)', 'userprofiles.views.Rest_Get_Thing_Elements', name='rest_get_thing_elements'),
    url(r'^rest_order_controller/', 'userprofiles.views.rest_order_controller', name='rest_order_controller'),

    url(r'^$', 'userprofiles.views.home', name='home'),



)

urlpatterns += [
    url(r'^api-token-auth/', views.obtain_auth_token)
]

Django/userprofiles/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
from things.models import Thing, AutomaticController
from cameras.models import Camera


class User_Profile(models.Model):
	user = models.OneToOneField(User)
	image = models.ImageField(upload_to='image_profile',null=True, blank = True)
	things = models.ManyToManyField(Thing,null=True, blank=True)
	cameras = models.ManyToManyField(Camera,null=True, blank=True)
	automaticcontrollers = models.ManyToManyField(AutomaticController,null=True,blank=True)

	def __unicode__(self):
		return self.user.username

Django/userprofiles/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from userprofiles.models import User_Profile
from rest_framework.authtoken.models import Token

class UserCreationEmailForm(UserCreationForm):
	email= forms.EmailField()

	class Meta:
		model = User
		fields = ('username','email')
		
class UserProfileCreationForm(forms.ModelForm):
	class Meta:
		model = User_Profile
		fields = ('image',)
	def save(self, user):
		user_profile = User_Profile(user=user,image=self.cleaned_data["image"])
		user_profile.save()
		token = Token.objects.create(user=user)
		return user_profile



class EmailAuthenticationForm(forms.Form):
	username = forms.CharField(label="Email")
	password = forms.CharField(label="Password",widget=forms.PasswordInput)

	def __init__(self, *args, **kwargs):
		self.user_cache = None
		super(EmailAuthenticationForm,self).__init__(*args,**kwargs)

	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')

		self.user_cache = authenticate(username=username,password=password)

		if self.user_cache is None:
			raise forms.ValidationError('Usuario Incorrecto')
		elif not self.user_cache.is_active:
			raise forms.ValidationError('Usuario Inactivo')

		return self.cleaned_data 


	def get_user(self):
		return self.user_cache				

Django/userprofiles/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout
from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.contrib.auth import authenticate
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.decorators import *
from rest_framework.renderers import JSONRenderer
from rest_framework.authtoken.models import Token
import json
import requests


# Create your views here.
from .forms import UserCreationEmailForm, EmailAuthenticationForm, UserProfileCreationForm
from .models import User_Profile
from things.models import *
from cameras.models import *



def entry(request):
	user_form = UserCreationEmailForm(request.POST or None)
	profile_form = UserProfileCreationForm(request.POST,request.FILES or None)
	signin_form = EmailAuthenticationForm(request.POST or None)
	
	if user_form.is_valid() and profile_form.is_valid():
		profile_form.save(user_form.save())
		return HttpResponseRedirect('/signin')

	if signin_form.is_valid():
		login(request,signin_form.get_user())
		return HttpResponseRedirect('/')

	return render(request, 'entry.html', {'user_form': user_form,'profile_form':profile_form,'signin_form':signin_form})


def logout_view(request):
	logout(request)
	return HttpResponseRedirect('/entry')



@login_required()
def home(request):
	profile = User_Profile.objects.get(user=request.user)

	return render(request,'home.html',{'profile':profile})


@csrf_exempt
def Rest_Login(request):
	if request.method == "OPTIONS": 
		response = HttpResponse()
		response['Access-Control-Allow-Origin'] = '*'
		response['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
		response['Access-Control-Max-Age'] = 1000
		# note that '*' is not valid for Access-Control-Allow-Headers
		response['Access-Control-Allow-Headers'] = 'origin, x-csrftoken, content-type, accept'
		return response

	if request.method == "POST":

		requestJsonData = bytes.decode(request.body)
		requestData = json.loads(requestJsonData)
		user_cache = authenticate(username=requestData['username'],password=requestData["password"])
		data = {}

		if not user_cache is None:
			data['token'] = Token.objects.get(user=user_cache).key
			data['username'] = user_cache.username
		else:
			data['success'] =False
		return HttpResponse(json.dumps(data), content_type = "application/json")


@api_view(['GET', 'OPTIONS',])
def Rest_Get_Things(request):
	if request.method == "OPTIONS": 
		response = HttpResponse()
		response['Access-Control-Allow-Origin'] = '*'
		response['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
		response['Access-Control-Max-Age'] = 1000
		# note that '*' is not valid for Access-Control-Allow-Headers
		response['Access-Control-Allow-Headers'] = 'origin, x-csrftoken, content-type, accept'
		return response

	if request.method == "GET": 
		user = TokenAuth(request)
		if not user is None:
			profile = User_Profile.objects.get(user = user)
			data = []
			for thing in profile.things.all():
				data.append({
					'id': thing.id,
					'name': thing.name,
					'key': thing .key, 
					})
			print data
			return HttpResponse(json.dumps(data), content_type = "application/json")
		return HttpResponse(json.dumps({'success': False}), content_type = "application/json")

@api_view(['GET', 'OPTIONS',])
def Rest_Get_Thing_Elements(request, id):
	if request.method == "OPTIONS": 
		response = HttpResponse()
		response['Access-Control-Allow-Origin'] = '*'
		response['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
		response['Access-Control-Max-Age'] = 1000
		# note that '*' is not valid for Access-Control-Allow-Headers
		response['Access-Control-Allow-Headers'] = 'origin, x-csrftoken, content-type, accept'
		return response

	if request.method == "GET": 
		user = TokenAuth(request)
		if not user is None:
			profile = User_Profile.objects.get(user = user)
			thing = Thing.objects.get(id = int(id))
			if thing in profile.things.all():
				data = {
					'id': thing.id,
					'name': thing.name,
					'key': thing.key,
					'controllers': [{'id': controller.id, 'identifier': controller.identifier} for controller in thing.controllers.all()],
					'sensors': [{'id': sensor.id, 'identifier': sensor.identifier} for sensor in thing.sensors.all()],
				}
				return HttpResponse(json.dumps(data), content_type = "application/json")
		return HttpResponse(json.dumps({'success': False}), content_type = "application/json")



@api_view(['GET', 'OPTIONS',])
def Rest_Get_Cameras(request):

	if request.method == "OPTIONS": 
			response = HttpResponse()
			response['Access-Control-Allow-Origin'] = '*'
			response['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
			response['Access-Control-Max-Age'] = 1000
			# note that '*' is not valid for Access-Control-Allow-Headers
			response['Access-Control-Allow-Headers'] = 'origin, x-csrftoken, content-type, accept'
			return response

	if request.method == "GET": 
		user = TokenAuth(request)
		if not user is None:
			profile = User_Profile.objects.get(user = user)
			data = []
			for camera in profile.cameras.all():
				data.append({
					'id': camera.id,
					'name': camera.name,
					'key': camera.key, 
					})
			print data
			return HttpResponse(json.dumps(data), content_type = "application/json")
		return HttpResponse(json.dumps({'success': False}), content_type = "application/json")

@api_view(['POST', 'OPTIONS',])
def rest_order_controller(request):
	if request.method == "OPTIONS": 
		response = HttpResponse()
		response['Access-Control-Allow-Origin'] = '*'
		response['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
		response['Access-Control-Max-Age'] = 1000
		# note that '*' is not valid for Access-Control-Allow-Headers
		response['Access-Control-Allow-Headers'] = 'origin, x-csrftoken, content-type, accept'
		return response

	if request.method == 'POST':
		user = TokenAuth(request)
		if not user is None:
			profile = User_Profile.objects.get(user = user)
			requestJsonData = bytes.decode(request.body)
			requestData = json.loads(requestJsonData)
			print requestData
			key = requestData['key']
			value = requestData['value']
			identifier = requestData['identifier']
			thing = Thing.objects.get(key = key)

			if thing in profile.things.all():
				controller = Controller()

				for cont in thing.controllers.all():
					if cont.identifier == identifier:
						controller = Controller.objects.get(id = cont.id)
						break

				controller_value = Value()
				controller_value.value = value
				controller_value.save()
				controller.log_control.add(controller_value)

				data = {'key': key, 'identifier': identifier,'value':value}
				r = requests.post("http://localhost:8000/order_controller/", data=data)
				return HttpResponse(json.dumps({'success': True}), content_type = "application/json")
		return HttpResponse(json.dumps({'success': False}), content_type = "application/json")

def TokenAuth(request):
	token = request.META['HTTP_AUTHORIZATION'].split()[1]
	for tok in Token.objects.all():
		if tok.key == token:
			return tok.user
	return None

Django/userprofiles/templates/entry.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Sign Up</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static "libraries/SemanticUI-1.8.1/semantic.css" %}" >
	<script src="{% static "libraries/SemanticUI-1.8.1/semantic.js"%}" type="text/javascript"></script>
	<script src="{% static "libraries/jquery-2.1.3.js"%}" type="text/javascript"></script>
	<style type="text/css">
.main.container{
  background-color: #F7F7F7;
  width: 70%;
  margin: 0em auto;
  padding: 2em 2em 7em;
  z-index: 1;
	}
	</style>

</head>
<body>
<div class="main container">
<div class="html ui top attached segment container">
	<div class="ui two column middle aligned relaxed fitted stackable grid">
		<div class="column">
			<div class="ui form segment">
				<form action="/entry/" method="post">
					{% csrf_token%}
					<div class="field">
						<input type="text" id="id_username" name="username" placeholder="Nombre de Usuario">
					</div>
					<div class="field">
						<input type="email" id="id_email" name="email" placeholder="Email">
					</div>
					<div class="field">
						<input type="password" id="id_password1" name="password1" placeholder="Contraseña">
					</div>
					<div class="field">
						<input type="password" id="id_password2" name="password2" placeholder="Repita la Contraseña">
					</div>
					<div class="field">
						<input type="file" id="id_image" name="image">
					</div>
					<input type="submit" value="Registro" class="ui green submit button">


				</form>

			</div>
		</div>



		<div class="ui vertical divider">
			Or
		</div>
		<div class="column">
			<div class="ui form segment">
				<form action="/entry/" method="post">
					{% csrf_token%}
					<div class="field">
						<label>Email</label>
						<div class="ui left icon input">
							<input type="text" id="id_username" name="username" placeholder="Username or Email">
							<i class="user icon"></i>
						</div>
					</div>
					<div class="field">
						<label>Password</label>
						<div class="ui left icon input">
							<input type="password" id="id_password" name="password" placeholder="Contraseña">
							<i class="lock icon"></i>
						</div>
					</div>
					<input type="submit" value="Login" class="ui blue submit button">
				</form>
			</div>
			
		</div>

	</div>
	</div>
</div>
</body>
</html>

Django/userprofiles/templates/home.html
{% extends "base.html" %}
{%block title%}
Inicio
{% endblock %}


{% block headscripts %}
<script src="http://stuffcontrol.ddns.net:8000/socket.io/socket.io.js"></script>
{% endblock %}

{%block contentmain%}
	{% load staticfiles %}

  <div id="ContentThings" class="relative">
  <h2 class="ui header head2">
  <div class="content">
    Things
  </div>
</h2>
  <a href="/newthing">
  <div class="ui green button absolute button_add">
  <i class="add circle icon"></i>
  Añadir Thing
</div>
</a>
<div class="ui divided items">
{% for thing in profile.things.all %}
  <div class="item content_thing">
    <div class="ui tiny image">
      <img src="{% static "images/nonimage.png" %}">
    </div>
    <div class="middle aligned content">
      <a href="/thing/{{thing.id}}" class="header">{{thing.name}}
      <div id="{{thing.key}}_isconected" class="right"></div></a>
      <div class="meta">
        <span class="cinema"><b>Controles:</b> {{thing.controllers.count}}</span><br>
        <span class="cinema"><b>Sensores:</b>{{thing.sensors.count}}</span>
      </div>
      <div class="delete_home ui dropdown item">
          <i class="ellipsis vertical icon"></i>
          <div class="menu">
            <a href="/delete_thing/{{thing.id}}" class="item">Eliminar</a>
          </div>
        </div>
    </div>
  </div>
{% endfor %}
</div>
</div>


<br><br><br><br>
<div id="ContentCameras" class="relative">
  <h2 class="ui header head2">
  <div class="content">
    Camaras
  </div>
</h2>
  <a href="/newcamera">
  <div class="ui green button absolute button_add">
  <i class="add circle icon"></i>
  Añadir Camara
</div>
</a>
<div class="ui divided items">
{% for camera in profile.cameras.all %}
  <div class="item content_thing">
    <div class="ui tiny image">
      <img src="{% static "images/nonimage.png" %}">
    </div>
    <div class="middle aligned content">
      <a href="/camera/{{camera.id}}" class="header">{{camera.name}}
      <div id="{{camera.key}}_isconected" class="right"></div></a>

      <div class="delete_home ui dropdown item">
          <i class="ellipsis vertical icon"></i>
          <div class="menu">
          <a href="#" class="item">Editar</a>
            <a href="/delete_camera/{{camera.id}}" class="item">Eliminar</a>
          </div>
        </div>
    </div>
  </div>
{% endfor %}
</div>
</div>


<br><br><br>
<div id="automaticcontrollers"  class="ui styled fluid accordion">
  <div class="title">
      <i class="dropdown icon"></i>
      Controles Automáticos (<span id="num_automaticcontrollers">{{profile.automaticcontrollers.count}}</span>)
      <div class="item right">
        <i class="icon green plus pointer" onclick="ShowModal();"></i>
      </div>
    </div>
    <div class="content" id="table_automaticcontrollers">
    </div>
</div>









  <div class="ui modal">
    <i class="close icon"></i>
    <div class="header">
      Nuevo Control Automático
    </div>
    <div class="content ui form">
        <div class="field">
          <label>Sensor</label>
          <div class="three fields">
          <div class="field">
              <select id="thingsensor" class="ui dropdown" onchange="thingsensor_selected()">
              <option value="">Thing</option>
                {% for thing in profile.things.all%}
                <option value="{{thing.id}}">{{thing.name}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="field">
              <select id="select_sensor" class="ui dropdown">
              <option value="">Sensor</option>
              </select>
            </div>
            <div class="field">
              <input id="sensor_range" placeholder="Rango" type="text">
            </div>
          </div>
        </div>
        <div class="field">
          <label>Controlador</label>
          <div class="three fields">
          <div class="field">
              <select id="thingcontroller" class="ui dropdown" onchange="thingcontroller_selected()">
                <option value="">Thing</option>
                {% for thing in profile.things.all%}
                <option value="{{thing.id}}">{{thing.name}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="field">
              <select id="select_controller" class="ui dropdown">
                <option value="">Controlador</option>
              </select>
            </div>
            <div class="field">
              <input id="controller_value" placeholder="Valor" type="text">
            </div>
          </div>
        </div>
        <div class="field centrado">
          <div class="ui green button" onclick="add_automaticcontroller();">Añadir</div>
        </div>
    </div>
  </div>









{% endblock %}

{% block javascript %}
<script>

window.onload = get_AutomaticControllers();


$('.ui.accordion').accordion({
    exclusive: false
  });

$('.ui.checkbox')
  .checkbox()
;
$('.ui.modal')
  .modal()
;

function ShowModal(){
  $(".ui.modal").modal('show');
}

  var sensors = {};
  {%for thing in profile.things.all%}
    sensors["{{thing.name}}"] = {};
    {%for sensor in thing.sensors.all%}
      sensors["{{thing.name}}"]["{{sensor.identifier}}"] = {{sensor.id}};
    {% endfor%}
  {% endfor %}

  var controllers = {};
  {%for thing in profile.things.all%}
    controllers["{{thing.name}}"] = {};
    {%for controller in thing.controllers.all%}
      controllers["{{thing.name}}"]["{{controller.identifier}}"] = {{controller.id}};
    {% endfor%}
  {% endfor %}


  function thingsensor_selected(){
    var thingsensor = $("#thingsensor option:selected").text();
    $('#select_sensor').empty();
    var options = '<option value="">Sensor</option>';

    for(var sensor in sensors[thingsensor]){
      options += '<option value="'+sensors[thingsensor][sensor]+'">'+sensor+'</option>';
    }
    $('#select_sensor').append(options);

  }

  function thingcontroller_selected(){
        var thingcontroller = $("#thingcontroller option:selected").text();
    $('#select_controller').empty();
    var options = '<option value="">controller</option>';

    for(var controller in controllers[thingcontroller]){
      options += '<option value="'+controllers[thingcontroller][controller]+'">'+controller+'</option>';
    }
    $('#select_controller').append(options);
  }


    function add_automaticcontroller(){
    $.post("/add_automaticcontroller/",
    {
        thingcontroller: $("#thingcontroller option:selected").val(),
        thingsensor: $("#thingsensor option:selected").val(),
        controller: $("#select_controller option:selected").val(),
        sensor: $("#select_sensor option:selected").val(),
        value: $('#controller_value').val(),
        range: $('#sensor_range').val()

    },
    function(data, status){
        console.log(data);
        show_automaticcontroller(data);
        $(".ui.modal").modal('hide');
    });
  }

  function get_AutomaticControllers(){
    $.get("/get_automaticcontroller/",function(data, status){
        console.log(data);
        show_automaticcontroller(data);
    });

  }

    function change_check(value,id){
    $.get("/change_check/"+value+"/"+id,function(data, status){
        console.log(data);
    });

  }

  function ChangingCheck(id){
              if($('#check_'+id).checkbox('is checked')){
            change_check('0',id);
          }
          else{
            change_check('1',id);
          }
  }

  function delete_automatic(id,select){
  $.get("/delete_automatic/"+id,function(data, status){
        console.log(data);

        row = select.parent().parent().parent().parent()

        if($("#automatic_row").length != 0){
          row.remove();
        }
        else{
          $("#table_automaticcontrollers").empty();
        }

    });
}


  var socket = io.connect('http://stuffcontrol.ddns.net:8000');

  var things = [];
  {% for thing in profile.things.all %}
  things.push("{{thing.key}}");
  {% endfor %}
  {% for camera in profile.cameras.all %}
  things.push("{{camera.key}}");
  {% endfor %}

  socket.emit('joinserver','{{profile.user.username}}','user',things);

  socket.on('isconected', function(thing,value){
    if(value){
      $("#"+thing+"_isconected").empty();
      $("#"+thing+"_isconected").append("<i class='selected radio green icon'></i>");
      console.log(thing+" conectada");
    }
    else{
      $("#"+thing+"_isconected").empty();
      $("#"+thing+"_isconected").append("<i class='radio red icon'></i>");
      console.log(thing+" no conectada");
    }
  });

</script>




<script>


function show_automaticcontroller(data){


  if(data.length > 0){
    $("#table_automaticcontrollers").empty();

    var table = '<table class="ui compact definition table">';
    table +='<thead>';
    table +='<tr>';
    table +='<th></th>';
    table +='<th>Thing</th>';
    table +='<th>Sensor</th>';
    table +='<th>Range</th>';
    table +='<th>Thing</th>';
    table +='<th>Controlador</th>';
    table +='<th>Valor</th>';
    table +='<th></th>';
    table +='</tr>';
    table +='</thead>';
    table +='<tbody id = "content_tableautomatic">';
    table+='</tbody>';
    table+='</table>';

    $("#table_automaticcontrollers").append(table);

    var content = "";

    for(var i in data){

    content +='<tr class="automatic_row">';
    content +='<td class="collapsing">';
    content +='<div id="check_'+data[i]['id']+'" class="ui fitted toggle checkbox" onclick="ChangingCheck('+ data[i]['id'] +')">';
    content +='<input type="checkbox"> <label></label>';
    content +='</div>';
    content +='</td>';
    content +='<td>'+data[i]['sensorthing_name']+'</td>';
    content +='<td>'+data[i]['sensor_name']+'</td>';
    content +='<td>'+data[i]['range']+'</td>';
    content +='<td>'+data[i]['controllerthing_name']+'</td>';
    content +='<td>'+data[i]['controller_name']+'</td>';
    content +='<td>'+data[i]['value']+'</td>';
    content +='<td class="">'
    content +='<div class="delete_home ui dropdown item automatic_options">';
    content +='<i class="ellipsis vertical icon"></i>';
    content +='<div class="menu">';
    content +='<a href="#" class="item">Editar</a>';
    content +='<a onclick="delete_automatic('+data[i]['id']+',$(this))" class="item">Eliminar</a>';
    content +='</div>';
    content +='</div>';
    content +='</td>';
    content +='</tr>'


    }

     $("#content_tableautomatic").append(content);

     $('.ui.checkbox').checkbox();

     for(i in data){
      if(data[i]['active']){
      $('#check_'+data[i]['id']).checkbox('check');
      }

     }

  }

  $('.ui.dropdown').dropdown('hide');
  $('#num_automaticcontrollers').empty();
  $('#num_automaticcontrollers').append(data.length);


}


</script>

{% endblock %}